# This file should be kept in-sync with .travis.yml!

environment:
  FORCE_TEST_EXIT: true
  matrix:
    - SHARD_INDEX: 0
    - SHARD_INDEX: 1
    - SHARD_INDEX: 2
    - SHARD_INDEX: 3
    - SHARD_INDEX: 4

install:
  - ps: $env:DART_CHANNEL="stable"
  - ps: Invoke-WebRequest "https://storage.googleapis.com/dart-archive/channels/${env:DART_CHANNEL}/release/latest/sdk/dartsdk-windows-x64-release.zip" -OutFile "dart.zip"
  - ps: 7z.exe x dart.zip | out-null
  - ps: $env:Path += ";$pwd\dart-sdk\bin"
  - dart-sdk\bin\dart --version
  - choco install googlechrome

test_script:
  - pub get
  - dartfmt -n --set-exit-if-changed .
  - dartanalyzer --fatal-infos --fatal-warnings .
  - pub run test --preset travis --total-shards 5 --shard-index %SHARD_INDEX%

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - /feature\..*/

cache:
  - '%APPDATA%\Pub\Cache'
