# This file should be kept in-sync with .travis.yml!

environment:
  FORCE_TEST_EXIT: true
  matrix:
    - SHARD_INDEX: 0
    - SHARD_INDEX: 1
    - SHARD_INDEX: 2
    - SHARD_INDEX: 3
    - SHARD_INDEX: 4

install:
  - ps: $env:DART_CHANNEL="dev"
  - ps: Invoke-WebRequest "https://storage.googleapis.com/dart-archive/channels/${env:DART_CHANNEL}/release/latest/sdk/dartsdk-windows-x64-release.zip" -OutFile "dart.zip"
  - ps: 7z.exe x dart.zip -oC:\projects | out-null
  - ps: $env:Path += ";C:\projects\dart-sdk\bin"
  # Required when running browser tests.
  # - choco install googlechrome
  # - choco install firefox
  # - choco install phantomjs

build_script:
  - dart --version
  - pub get
  - dartfmt -n --set-exit-if-changed .
  - dartanalyzer --fatal-infos --fatal-warnings .

test_script:
  # Only run VM tests for now.
  - pub run test --preset vm --total-shards 5 --shard-index %SHARD_INDEX%

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - /feature\..*/
    - add-appveyor # For while testing and we'we don't have a PR..

cache:
  - '%APPDATA%\Pub\Cache'
